# Generated by Django 4.0.6 on 2022-08-03 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_event_user_events'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user_events',
        ),
        migrations.AddField(
            model_name='event',
            name='event_auth',
            field=models.ManyToManyField(related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
