# Generated by Django 4.0.6 on 2022-08-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_end_time_alter_event_start_time'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_events',
            field=models.ManyToManyField(blank=True, related_name='created_by', to='events.event'),
        ),
    ]
